# Generated by Django 5.0.1 on 2024-02-01 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0004_alter_contacts_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messanger.group'),
        ),
    ]
